bots:
    - class_name: '<add class name from psgroupme.bots.py here>'
      bot_name: '<add bot name here>'
      bot_id: '<add bot id hash here>'
      group_name: '<add bot group name here>'
      group_id: '<add bot group id here>'
      avatar_url: '<add URL to bot avatar here>'
      callback_url: '<add URL to bot callback here>'
